name: CID

on:
  workflow_dispatch:   # manual run
  schedule:
    - cron: "0 3 * * *"   # runs daily at 3 AM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv pandas google-auth google-api-python-client google-auth-httplib2 google-auth-oauthlib
      
      - name: Prepare GCP credentials
        run: |
          echo "${GCP_CREDENTIALS}" > gcp_key.json
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      
      - name: Run script
        env:
          KEKA_URL: ${{ secrets.KEKA_URL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          GRANT_TYPE: ${{ secrets.GRANT_TYPE }}
          SCOPE: ${{ secrets.SCOPE }}
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_ATTENDANCE: ${{ secrets.API_KEY_ATTENDANCE }}
          TEMPLATE_FILE_PATH_DICE: Dice_SFTP_Template.csv
          TEMPLATE_FILE_PATH: SFTP_File-Nephrocare-27dec.csv
          ATT_TEMPLATE_FILE_PATH: Attendance.csv
          TARGET_FILE_PATH: output
          PEM_PATH: nephroplus.ppk
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          mkdir -p output
          python attendance.py

      - name: Upload output CSV as GitHub artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: attendance-output
          path: output/*.csv
